### ISSUE TITLE
Report detail requirement and use case

### ISSUE THREAD

**Issue by joshherkness** [kdjohnson/destinationDelicious#15]
# Cart detail requirement and use case

- Create a requirements for report detail in the requirements capture ( should be R2.7)
- Create a preliminary use case for report detail in the requirements capture (should be UC2.6)
- Create a detailed use case for report detail in the requirements capture (should be UC2.6)

**Comment by nikole-flowers** [comment]
Added all three cases into the requirements capture - R2.7 and UC3.1
